### ISSUE TITLE
Interdomain NSM: BulkRegisterNSE registers endpoints with the wrong IP to NSMRS

### ISSUE THREAD

**Issue by terror96** [networkservicemesh/networkservicemesh#2142] opened 2020-04-17 12:14 UTC
## Expected Behavior

In the interdomain NSM case, we can launch a client that connects to an endpoint in another cluster. We repeat it after NSE_TRACKING_INTERVAL interval, and a new client should still be able to connect to the endpoint.

## Current Behavior

We have tested the interdomain NSM case, and it works for 2 minutes (matches with NSE_TRACKING_INTERVAL). After this, launching clients fails. 

It seems that the initial endpoint registration to NSMRS is correct, but subsequent updates (i.e. BulkRegisterNSE messages) are incorrect. Invalid registration information about the endpoint seems to point to an invalid IP address i.e. the NSMgr address is a pod network address instead of a public address (required in the interdomain case).

## Failure Information (for bugs)

A new client launch is stuck in 'Init:1/2'.

## Steps to Reproduce

Cluster 1
Deploy nsmrs, nsm, proxy-nsmgr with helm
Deploy one endpoint

Cluster 2
Deploy nsm, proxy-nsmgr with helm
Deploy one client
wait for 3 minutes, deploy another client

## Context

* Kubernetes Version: Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8"
* NSM: commit 8d64ff42c90d420c60b06be91cf16b45eb8ac781

## Failure Logs

extract from nsmrs log (still valid):

time="2020-04-16T11:41:54Z" level=info msg=">><<-- response={\"payload\":\"IP\",\"network_service\":{\"name\":\"simple-demo\",\"payload\":\"IP\"},\"network_service_managers\":{\"k8s2-2_10.1.0.18_5001\":{\"name\":\"k8s2-2_10.1.0.18_5001\",\"url\":\"10.1.0.18:5001\",\"expiration_time\":{\"seconds\":1587037573},\"state\":\"RUNNING\"}},\"network_service_endpoints\":[{\"name\":\"simple-demor6n48\",\"payload\":\"IP\",\"network_service_name\":\"simple-demo\",\"network_service_manager_name\":\"k8s2-2_10.1.0.18_5001\",\"labels\":{\"app\":\"demo-gateway\",\"networkservicename\":\"simple-demo\"},\"state\":\"RUNNING\"}]} span=2e717a67266014a5:2e717a67266014a5:0:1"

(cut)

time="2020-04-16T11:47:13Z" level=info msg="Received BulkRegisterNSE request: network_service:<name:\"simple-demo\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2\" url:\"10.243.1.16:5001\" state:\"RUNNING\" > network_service_endpoint:<name:\"simple-demor6n48\" payload:\"IP\" network_service_name:\"simple-demo\" network_service_manager_name:\"k8s2-2\" labels:<key:\"app\" value:\"demo-gateway\" > labels:<key:\"networkservicename\" value:\"simple-demo\" > state:\"RUNNING\" > " operation=Nsmrs.BulkRegisterNSE span="620b07ac28581d4d:6d9d2d4999f7573:620b07ac28581d4d:1"

**Comment by terror96** [comment] 2020-04-17 13:00
It appears that proxy-nsmgr modifies the address (look for comment 'Swapping IP address to external') in k8s/pkg/proxyregistryserver/registry.go::RegisterNSE(), but not in ::BulkRegisterNSE(). Could this be the root cause of problem?

**Comment by denis-tingajkin** [comment] 2020-04-26 07:07
@terror96 

Hello, I tried to reproduce the problem via go tests and kind clusters and it is not reproduced for me with steps below.

**Steps to reproduce:**

1.Deploy `nsmrs`, `nsm`, `proxy-nsmgr`, `nse` with networks service `icmp-responder` on cluster1
3.Deploy `nsm`, `proxy-nsmgr`, `nsc-1` with `CLIENT_NETWORK_SERVICE=icmp-responder@CLUSTER1_NODE_IP` on cluster 2
3. Check that `nsc-1` can ping `nse`
4. Wait 3 min
5. Deploy `nsc-2` with  `CLIENT_NETWORK_SERVICE=icmp-responder@CLUSTER1_NODE_IP` on cluster2
6. Check that `nsc-2` can ping `nse`

**Actual**: `nsc-2` can ping  `nse`
**Expected**: `nsc-2` can ping  `nse`

Can you please verify my steps? If they are correct then could you please attach your helm steps?

**Comment by terror96** [comment] 2020-04-27 09:23
There seems to be an error in the provided steps to reproduce. Also, the initial conclusion that the situation emerges after NSE_TRACKING_INTERVAL is wrong. Sorry about that. It takes a bit longer,
even pass the value of NSE_EXPIRATION_TIMEOUT.

However, it seems that the sequence is as follows: initial registration (works), bulk registrations (with the wrong address) but the initial entry still in the cache, and the initial registration times out (Q: why does the entry time out?). If a client is then started, it will get a pointer to the wrong IP address.

In the below, the endpoint is in cluster 2 and the clients in cluster 1.

Setup:
Two k8s clusters in OpenStack VMs

Code:
https://github.com/networkservicemesh/networkservicemesh.git -> ./networkservicemesh
https://github.com/tiswanso/examples.git -> ./networkservicemesh/examples

**cluster 1**

$ helm install --set spire.enabled="False" --namespace default --set insecure=true ./networkservicemesh/deployments/helm/nsmrs

**cluster 1 & 2**

$ helm install --set spire.enabled="False" --namespace default --set insecure=true ./networkservicemesh/deployments/helm/nsm

> Note! Make sure NSMRS_ADDRESS points to nsmrs (in our case: 10.1.0.24:5010), which seems to be missing from the helm chart.

$ helm install --set spire.enabled="False" --namespace default --set insecure=true ./networkservicemesh/deployments/helm/proxy-nsmgr

**cluster 2**

$ kubectl apply -f ./networkservicemesh/examples/examples/icmp/k8s/simple-endpoint.yaml

**cluster 1**

$ kubectl logs nsmrs-... --follow

time="2020-04-27T07:24:34Z" level=info msg="Received RegisterNSE(network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2\" url:\"**10.1.0.18:5001**\" state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-responders96g6\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > )" operation=Nsmrs.RegisterNSE span="3fec3b413c5229b9:513292a630a7bc92:3fec3b413c5229b9:1"                                                               

(cut)

time="2020-04-27T07:26:34Z" level=info msg="Received BulkRegisterNSE request: network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2\" url:\"**10.243.1.140:5001**\" state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-responders96g6\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=Nsmrs.BulkRegisterNSE span="46f64d2ac7275509:23ac612e0c07026d:46f64d2ac7275509:1"

(cut)

time="2020-04-27T07:30:34Z" level=info msg="Received BulkRegisterNSE request: network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2\" url:\"**10.243.1.140:5001**\" state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-responders96g6\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=Nsmrs.BulkRegisterNSE span="750dfd0cd9e9cc0c:4b08c649cf0b88e7:750dfd0cd9e9cc0c:1"

(cut)

time="2020-04-27T07:31:46Z" level=info msg="Network Service Endpoint removed by timeout : network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2_10.1.0.18_5001\" url:\"**10.1.0.18:5001**\" expiration_time:<seconds:1587972574 > state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-responders96g6\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.1.0.18_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=NsmrsCache.StartNSMDTracking span="2fdf0968575f7382:2fdf0968575f7382:0:1"

**cluster 1**

> Make sure CLIENT_NETWORK_SERVICE=icmp-responder@10.1.0.24

$ kubectl apply -f ./networkservicemesh/examples/examples/icmp/k8s/simple-client.yaml

**cluster 1**

$ kubectl logs nsmrs-... --follow

time="2020-04-27T07:32:51Z" level=info msg="FindNetworkService done: payload:\"IP\" network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_managers:<key:\"k8s2-2_10.243.1.140_5001\" value:<name:\"k8s2-2_10.243.1.140_5001\" url:\"**10.243.1.140:5001**\" expiration_time:<seconds:1587974019 > state:\"RUNNING\" > > network_service_endpoints:<name:\"icmp-responders96g6\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.243.1.140_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > network_service_endpoints:<name:\"icmp-responderhphfn\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.243.1.140_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=Nsmrs.FindNetworkService span="451215693cb5857b:9827c363b1c13be:451215693cb5857b:1"
2020/04/27 07:32:51 Reporting span 451215693cb5857b:9827c363b1c13be:451215693cb5857b:1
time="2020-04-27T07:49:51Z" level=info msg=">><<-- response={\"payload\":\"IP\",\"network_service\":{\"name\":\"icmp-responder\",\"payload\":\"IP\"},\"network_service_managers\":{\"k8s2-2_10.243.1.140_5001\":{\"name\":\"k8s2-2_10.243.1.140_5001\",\"url\":\"10.243.1.140:5001\",\"expiration_time\":{\"seconds\":1587974019},\"state\":\"RUNNING\"}},\"network_service_endpoints\":[{\"name\":\"icmp-responders96g6\",\"payload\":\"IP\",\"network_service_name\":\"icmp-responder\",\"network_service_manager_name\":\"k8s2-2_10.243.1.140_5001\",\"labels\":{\"app\":\"simple-endpoint\",\"networkservicename\":\"icmp-responder\"},\"state\":\"RUNNING\"},{\"name\":\"icmp-responderhphfn\",\"payload\":\"IP\",\"network_service_name\":\"icmp-responder\",\"network_service_manager_name\":\"k8s2-2_10.243.1.140_5001\",\"labels\":{\"app\":\"simple-endpoint\",\"networkservicename\":\"icmp-responder\"},\"state\":\"RUNNING\"}]} span=451215693cb5857b:451215693cb5857b:0:1"

**Comment by denis-tingajkin** [comment] 2020-05-13 05:03
@terror96 Could you please check this problem with the latest master?
 If it is reproducible then please attach logs from `nsmrs`, `nsmd-k8s`  from nsmgr and `proxy-nsmd-k8s` from pnsmgr.

**Comment by terror96** [comment] 2020-05-13 13:43
We are experiencing the same result.

This time we only launched the endpoint (2 instances) and waited until the registration times out (entry with IP=10.1.0.18:5001) thus leaving only the invalid entry in nsmrs (entry with IP=10.243.1.140:5001). The IP addresses are identical to the above description.

Q: why does the registration time out in nsmrs? The associated endpoint is up and running. There is possibly something going on related to this: see errors in proxy-nsmd-k8s.log. However, nsmrs seems to receive these BulkRegisterNSE messages. Should it send something back?

The nsmrs log is from cluster1, and the other two from cluster2 where we launched the endpoint (2 instances).

[nsmd-k8s.log](https://github.com/networkservicemesh/networkservicemesh/files/4622201/nsmd-k8s.log)
[nsmrs-ff76f9954-svc9x.log](https://github.com/networkservicemesh/networkservicemesh/files/4622203/nsmrs-ff76f9954-svc9x.log)
[proxy-nsmd-k8s.log](https://github.com/networkservicemesh/networkservicemesh/files/4622205/proxy-nsmd-k8s.log)

**Comment by denis-tingajkin** [comment] 2020-05-13 16:50
@terror96 thanks for the logs!
Yes, I also found here an interesting moment... 
Note at this lines from the nsmgr logs
```
time="2020-05-13T13:14:11Z" level=info msg="Registered NSE entry network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2_10.1.0.18_5001\" url:\"10.1.0.18:5001\" expiration_time:<seconds:1589375951 > state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-respondernsnx8\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.1.0.18_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > "
time="2020-05-13T13:14:11Z" level=info msg="Registered NSE entry network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2_10.1.0.18_5001\" url:\"10.1.0.18:5001\" expiration_time:<seconds:1589375951 > state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-respondertkccr\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.1.0.18_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > "

...
Received few BulkRegisterNSE requests...
...
time="2020-05-13T13:20:30Z" level=info msg="Network Service Endpoint removed by timeout : network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2_10.1.0.18_5001\" url:\"10.1.0.18:5001\" expiration_time:<seconds:**1589375951** > state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-respondernsnx8\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.1.0.18_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=NsmrsCache.StartNSMDTracking span="19ac190db350362a:19ac190db350362a:0:1"
time="2020-05-13T13:20:30Z" level=info msg="Network Service Endpoint removed by timeout : network_service:<name:\"icmp-responder\" payload:\"IP\" > network_service_manager:<name:\"k8s2-2_10.1.0.18_5001\" url:\"10.1.0.18:5001\" expiration_time:<seconds:**1589375951** > state:\"RUNNING\" > network_service_endpoint:<name:\"icmp-respondertkccr\" payload:\"IP\" network_service_name:\"icmp-responder\" network_service_manager_name:\"k8s2-2_10.1.0.18_5001\" labels:<key:\"app\" value:\"simple-endpoint\" > labels:<key:\"networkservicename\" value:\"icmp-responder\" > state:\"RUNNING\" > " operation=NsmrsCache.StartNSMDTracking span="19ac190db350362a:19ac190db350362a:0:1"
``` 
As you can see here time on starting and on removing is equal(1589375951 is time of registratin)
By some reason received BulkRegisterNSE requests not updated ExpirationTime...

If you have chance then could you add additional log here https://github.com/networkservicemesh/networkservicemesh/blob/9a17692e4a5bfc324d6b500459f8f1a39c6dcd7f/applications/nsmrs/pkg/serviceregistryserver/cache.go#L89 and check is time changed on receiving BulkRegisterNSE request?

**Comment by denis-tingajkin** [comment] 2020-06-01 09:34
The problem is unreproducible on kind clusters.

@terror96 we've expanded logs, so if you have a chance then please attach logs from `nsmrs` container from latest image.
 Note: Probably you need to update your images:
```make
make docker-save k8s-load-images
```

Also, a question, what the cluster you are used?

**Comment by terror96** [comment] 2020-06-16 12:57
We are not using "kind" but our setup consists of 4 OpenStack virtual machines. There are two k8s clusters (cluster 1 and cluster 2) with 2 VMs in each. One master and one slave.

Here is the log file of nsmrs with the code base at 9d2d6b6c9a559ad99c6628c362089b07d3f64d75:

[nsmrs.log](https://github.com/networkservicemesh/networkservicemesh/files/4786571/nsmrs.log)

Just for the fun of it, we modified the code in nsmd (controlplane/pkg/nsmd/nsmd.go) to set the NetworkServiceManager's IP address to a hard-coded address, i.e. replaced GetPublicAPI() with a hard-coded address. In this case, we know the pod is scheduled on 10.1.0.18 and thus we used that address. This is not the proper way to fix the problem, but this produces the attached log:

[nsmrs-fixed.log](https://github.com/networkservicemesh/networkservicemesh/files/4786575/nsmrs-fixed.log)

Now the bulk update messages match with the entry in the db, and the expiration time is updated:

time="2020-06-16T12:22:51Z" level=info msg="Updated expiration time seconds:1592310351  -> seconds:1592310471  for entry network_service:<name:\"icmp-responder\"

This is not visible in the first attached log.

We previously noted the following:

"It appears that proxy-nsmgr modifies the address (look for comment 'Swapping IP address to external') in k8s/pkg/proxyregistryserver/registry.go::RegisterNSE(), but not in ::BulkRegisterNSE(). Could this be the root cause of problem?"

**Comment by denis-tingajkin** [comment] 2020-06-16 13:33
I tried to reproduce the problem on all clusters https://github.com/networkservicemesh/networkservicemesh/pull/2166 and it is not reproducing. Could you check the steps? Probably I missed something...


> We are not using "kind" but our setup consists of 4 OpenStack virtual machines. There are two k8s clusters (cluster 1 and cluster 2) with 2 VMs in each. One master and one slave.

Ok, cool will try to reproduce the problem with this setup. 

> It appears that proxy-nsmgr modifies the address (look for comment 'Swapping IP address to external') in k8s/pkg/proxyregistryserver/registry.go::RegisterNSE(), but not in ::BulkRegisterNSE(). Could this be the root cause of problem?

Yes, you probably right, but I want to reproduce it at first.

**Comment by denis-tingajkin** [comment] 2020-06-29 03:23
@terror96 Reproduced and fixed in #2168, can you please check?

**Closed** 2020-07-07 14:36 UTC
Labels: bug :bug:

**Comment by terror96** [comment] 2020-07-10 11:37
Sorry for the late response, but thank you. I can now confirm that the bug fix works also in our testbed.

**Comment by denis-tingajkin** [comment] 2020-07-10 13:17
@terror96 It was a super unobvious problem. Your logs and investigation super helped to understand what's going on. Thanks 👍

**Comment by terror96** [comment] 2020-07-17 09:27
> @terror96 It was a super unobvious problem. Your logs and investigation super helped to understand what's going on. Thanks

Great to hear and thank you for looking into this.
