### ISSUE TITLE
CI unstable on master Example-helm-vpn

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1532] opened 2019-08-22 19:45 UTC
## Expected Behavior

CI is expected to pass reliably on master.

## Current Behavior

CI is failing intermittently on master

## Failure Information (for bugs)

https://circleci.com/gh/networkservicemesh/networkservicemesh/92559
https://circleci.com/gh/networkservicemesh/networkservicemesh/92558

**Comment by denis-tingajkin** [comment] 2019-08-23 09:48
Test `TestDNSMonitoringNsc` will be fixed by this PR: https://github.com/networkservicemesh/networkservicemesh/pull/1521
For now  `TestDNSMonitoringNsc`  disabled on master

**Comment by artem-belov** [comment] 2019-08-30 09:38
TestInterdomainNSMHealRemoteDieNSMD fixed with pr #1538

**Comment by haiodo** [comment] 2019-09-10 14:19
Reproduced with:
https://circleci.com/gh/networkservicemesh/networkservicemesh/98623?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment] 2019-09-18 13:01
duplicate of https://github.com/networkservicemesh/networkservicemesh/issues/1623

**Comment by haiodo** [comment] 2019-09-23 09:10
Closing since it is duplicate to #1623

**Closed by haiodo** 2019-09-23 09:10 UTC
