### ISSUE TITLE
Metrics: crossconnect-monitor doesn't report metrics

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#2055] opened 2020-01-15 10:44 UTC
## Expected Behavior

The crossconnect-monitor should report metrics in update messages

## Current Behavior

No update messages are reported in the logs

## Steps to Reproduce

I'm deploying nsm and the icmp-responder example with kind.
I'm using k8s-check to generate icmp traffic between nsc and nse.

The icmp logs don't show any update message and no metrics.
I've also deployed prometheus, but no metrics data are reported to prometheus.

**Comment by denis-tingajkin** [comment] 2020-01-15 14:50
Hello @matrohon.
Did you use a kernel forwarder?

**Comment by matrohon** [comment] 2020-01-16 07:48
@denis-tingajkin I used the default forwarder which is vpp.

**Comment by denis-tingajkin** [comment] 2020-01-21 09:38
Looks like it is the same issue as https://github.com/networkservicemesh/networkservicemesh/issues/1512
And we have the fix for this issue https://github.com/networkservicemesh/networkservicemesh/pull/1983
But we can't merge it right now, because at first, we need to wait for a new release from vpp-agent guys with fix for https://github.com/ligato/vpp-agent/issues/1590

**Comment by matrohon** [comment] 2020-01-21 12:51
@denis-tingajkin @ivanayov thanks for investigations, I thought it was already available with the vpp-agent used by nsm.

**Comment by ivanayov** [comment] 2020-01-21 12:52
I reproduced with vpp, with the kernel-forwarder metrics are tracked. 
So it's most probably the issue @denis-tingajkin mentioned.

**Closed** 2020-02-27 13:16 UTC
Labels: wontfix
