### ISSUE TITLE
NsmMonitorCrossConnectClient throws `fatal error: concurrent map writes`

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#1398] opened 2019-07-28 17:03 UTC
## Expected Behavior

Tests should not fail.

## Current Behavior

` TestHealRemoteNSE` failed at least once with:

```
fatal error: concurrent map writes
fatal error: concurrent map writes
```

## Failure Information (for bugs)

[Full log](https://circleci.com/gh/networkservicemesh/networkservicemesh/82890?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

**Comment by onobrod** [comment] 2019-07-29 03:30
Duplicate of https://github.com/networkservicemesh/networkservicemesh/issues/1237

**Comment by edwarnicke** [comment] 2019-07-30 14:13
@nickolaev Mind if we close this as a duplicate of #1237

**Closed** 2019-08-13 14:09 UTC
