### ISSUE TITLE
Invalid memory address or nil pointer dereference on packetInstance destroy 

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1467] opened 2019-08-13 06:00 UTC
## Expected Behavior

cloudtest doesn't throws exceptions on packetInstance destroy 

## Current Behavior

sometimes throws Invalid memory address or nil pointer dereference exception on packetInstance destroy 

## Failure Logs
```
ERRO[3176] Failed to create ssh key POST https://api.packet.net/projects/383890d0-f5d1-4de1-881a-4d1ede549d18/ssh-keys: 422 Key already exists  
INFO[3176] Destroying cluster  packet-1                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10cff20]

goroutine 6161 [running]:
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/providers/packet.(*packetInstance).Destroy(0xc000230d00, 0x8bb2c97000, 0x8bb2c97000, 0x0)
	/home/circleci/project/test/cloudtest/pkg/providers/packet/packet_provider.go:372 +0xf0
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).destroyCluster(0xc000102c00, 0xc00025b900, 0x1)
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:797 +0xf0
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster.func1(0xc000102c00, 0xc00025b900, 0xc000457720)
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:709 +0xe0
created by github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:700 +0x16b
Exited with code 2
```
source:
https://circleci.com/gh/networkservicemesh/networkservicemesh/87768?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by haiodo** [comment] 2019-08-13 09:08
Duplicate of #1435

**Closed by haiodo** 2019-08-13 09:08 UTC
