### ISSUE TITLE
Building and run NSM on ARM64

### ISSUE THREAD

**Issue by stanislav-chlebec** [networkservicemesh/networkservicemesh#809] opened 2019-03-06 21:14 UTC
We're tracking here the efforts to run NSM on an ARM64 board. A couple of issues have been observed so far, mainly with the way we use `vpp/vppagent`. The target is to have a minimal NSMgr + Dataplane deployment, which can accommodate NetworkServices Endpoints and Clients.

#828 treats the basic image build (no cross compilation).

-------------------------------------------------------------------------------------
Original text:
Hello 
I am Stanislav Chlebec from Pantheon Tech company.
I have built the set of networkservicemesh docker images for AMR64 platform.
Could you please allow me to push these images to your repo?
Thanks

**Comment by edwarnicke** [comment] 2019-03-06 22:57
@stanislav-chlebec Is it possible for us to build them as part of our CI and push them ourselves?

**Comment by stanislav-chlebec** [comment] 2019-03-07 07:07
@edwarnicke  Good idea. I will prepare and upload scripts. But currently I build on ARM64 platform. I have no scripts for crosscompilation....

**Comment by nickolaev** [comment] 2019-03-07 07:52
@stanislav-chlebec should be pretty easy to do this form our CI. We need QEMU arm static to do the translation, and the build will be pretty slow. Check this link:
https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/

I suggest we put this in a separate job and call it only for `master` similar to our `docker-push-latest` job https://github.com/networkservicemesh/networkservicemesh/blob/master/.circleci/config.yml#L364


I would be interested in your environment, what machines do you use and what you were able to test/try? Did you manage to figure out the download of a working VPP image or are you building it yourself?

Our CI runs in Packet where we can potentially get ARM hosts too, although probably we'll postpone this after the release in May.

**Comment by rdimitrov** [comment] 2019-03-07 09:43
Hey, @stanislav-chlebec
Nice effort 👍 I also built the NSM images for ARM64 before and it went without any issues. I faced some problems with the VPP related images though - there were no consistent images pushed, so had to build one from source. It would be interesting to share how you manage to overcome that and run NSM at the end? 

As far as building on non-ARM64 hardware, if everything is pure Go perhaps we should be able to use the native cross-compilation of `go build` for ARM64, for ex. 
```
GOOS=linux GOARCH=arm64 go build
```

**Comment by stanislav-chlebec** [comment] 2019-03-07 10:23
@nickolaev environment: ThunderX ARM64
I only begin with this project - I was able to build docker images via make k8s-save command.
Before that  I had prepared https://cloud.docker.com/u/ligato/repository/docker/ligato/vpp-agent-arm64 with tag v1.8.1 and had changed the docker image in Dockerfiles.*

**Comment by stanislav-chlebec** [comment] 2019-03-07 10:41
@nickolaev the ThunderX machine was provided by packet

**Comment by stanislav-chlebec** [comment] 2019-03-07 10:44
@rdimitrov Currently there are built ARM64 images - see 
https://cloud.docker.com/u/ligato/repository/docker/ligato/dev-vpp-agent-arm64
https://cloud.docker.com/u/ligato/repository/docker/ligato/vpp-agent-arm64
latest should by up to date

**Comment by rdimitrov** [comment] 2019-03-07 13:38
@stanislav-chlebec Thanks! 
I decided to do a quick test, so I built and tried on ARM64 the latest NSM images with [ligato/vpp-agent-arm64:v1.8.1](https://hub.docker.com/r/ligato/vpp-agent-arm64/tags), but it failed on my side with the following error from the VPP agent - 
```
"VPPApiError: Initialization Failed (-144)" loc="ifplugin/interface_config.go(1012)
```
Here are the full logs from that run - 
* [vppagent-dataplane](https://gist.github.com/rdimitrov/7b0347c869db3468a822a5f5b85790d8)
* [nsmd-nsmd](https://gist.github.com/rdimitrov/d41666b30732a965658d1fa19fd4f644)

**Comment by stanislav-chlebec** [comment] 2019-03-07 21:25
I tried ligato/vpp-agent-arm64:dev

  505  sudo kubeadm init --token-ttl 0 --pod-network-cidr=10.1.0.0/16
  506  mkdir -p $HOME/.kube
  507  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  508  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  509  kubectl get pods -n kube-system
  510  docker pull contivvpp/vswitch-arm64:latest
  511  docker pull contivvpp/ksr-arm64:latest
  512  docker pull contivvpp/cni-arm64:latest
  513  docker pull contivvpp/stn-arm64:latest
  514  docker pull contivvpp/crd-arm64:latest
  515  docker pull contivvpp/ui-arm64:latest
  516  mkdir contivppnetwork
  517  cd contivppnetwork/
  518  git clone https://github.com/contiv/vpp.git
  519  cd vpp/k8s/contiv-vpp/
  520  ls
  521  helm template --name my-release ../contiv-vpp -f ./values-latest.yaml,./values-arm64.yaml,./values.yaml --set vswitch.defineMemoryLimits=true --set vswitch.hugePages1giLimit=8Gi --set vswitch.memoryLimit=8Gi   > manifest-arm64.yaml3
  522  ls
  523  kubectl apply -f manifest-arm64.yaml3


  527  kubectl get pods -n kube-system -o wide

  533  cd work/
  534  cd networkservicemesh/
  536  git diff
  537  vim .mk/docker.mk  # edited to use ligato/vpp-agent-arm64:dev in building of nsm docker images – will be git push...
  538  make k8s-save
  539  ls
  540  vim arm64_docker_images
  541  bash arm64_docker_images # to push to https://cloud.docker.com/u/stanislavchlebec/repository/list
  542  docker login
  543  docker login
  544  bash arm64_docker_images
  545  cat arm64_docker_images


  547  kubectl get pods -n kube-system -o wide
  548  cd k8s/conf/
  549  ls
  550  cat nsmd.yaml
  551  kubectl create -f nsmd.yaml
  552  kubectl get pods -n kube-system -o wide
  553  kubectl get pods
  554  ls
  555  kubectl create -f vppagent-dataplane.yaml
  556  kubectl get pods
  566  kubectl get pods
  567  ls
  568  kubectl create -f icmp-responder-nse.yaml
  569  kubectl get pods
  584  kubectl get pods
  585  history

Here after deploying icmp-responder-nse I got errorneous state:
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          9m35s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          9m35s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   6          12m
nsmd-jvh7p                            2/3     CrashLoopBackOff   8          13m
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods -n kube-system -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE        NOMINATED NODE   READINESS GATES
contiv-crd-8sswb                    1/1     Running   0          73m   147.75.72.194   contivvpp   <none>           <none>
contiv-etcd-0                       1/1     Running   0          73m   147.75.72.194   contivvpp   <none>           <none>
contiv-ksr-cmg8z                    1/1     Running   0          73m   147.75.72.194   contivvpp   <none>           <none>
contiv-vswitch-ns7hr                1/1     Running   0          73m   147.75.72.194   contivvpp   <none>           <none>
contiv-vswitch-qcwdc                1/1     Running   0          72m   147.75.98.202   vppagent    <none>           <none>
coredns-86c58d9df4-5xc4j            1/1     Running   0          79m   10.1.1.3        contivvpp   <none>           <none>
coredns-86c58d9df4-8dm85            1/1     Running   0          79m   10.1.1.2        contivvpp   <none>           <none>
etcd-contivvpp                      1/1     Running   0          79m   147.75.72.194   contivvpp   <none>           <none>
kube-apiserver-contivvpp            1/1     Running   0          79m   147.75.72.194   contivvpp   <none>           <none>
kube-controller-manager-contivvpp   1/1     Running   0          79m   147.75.72.194   contivvpp   <none>           <none>
kube-proxy-jkzht                    1/1     Running   0          79m   147.75.72.194   contivvpp   <none>           <none>
kube-proxy-wb9j7                    1/1     Running   0          72m   147.75.98.202   vppagent    <none>           <none>
kube-scheduler-contivvpp            1/1     Running   0          79m   147.75.72.194   contivvpp   <none>           <none>
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$

**Comment by stanislav-chlebec** [comment] 2019-03-07 21:32
Here you can see that after some period ligato/vpp-agent-arm64:dev which is of version 2 of developping was running
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
nsmd-jvh7p   3/3     Running   0          30s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ ls
admission-webhook-cfg.yaml  cluster-role-view.yaml        crossconnect-monitor.yaml  nsc.yaml                          vpn-gateway-nsc.yaml      vppagent-icmp-responder-nse.yaml
admission-webhook.yaml     crd-networkserviceendpoints.yaml  debug                nsmd.yaml                         vpn-gateway-nse.yaml      vppagent-nsc.yaml
cluster-role-admin.yaml     crd-networkservicemanagers.yaml   icmp-responder-nse.yaml    secure-intranet-connectivity.yaml  vppagent-dataplane.yaml
cluster-role-binding.yaml   crd-networkservices.yaml             jaeger.yaml             skydive.yaml                      vppagent-firewall-nse.yaml
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl create -f vppagent-dataplane.yaml
daemonset.extensions/nsm-vppagent-dataplane created
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   0/1     Running   0          4s
nsmd-jvh7p                     2/3     Error     0          77s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   0/1     Running   0          9s
nsmd-jvh7p                     2/3     Error     1          82s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS             RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running            0          22s
nsmd-jvh7p                     2/3     CrashLoopBackOff   1          95s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          25s
nsmd-jvh7p                     2/3     Running   2          98s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          29s
nsmd-jvh7p                     2/3     Running   2          102s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          33s
nsmd-jvh7p                     2/3     Running   2          106s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          37s
nsmd-jvh7p                     2/3     Running   2          110s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          39s
nsmd-jvh7p                     3/3     Running   2          112s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   0          43s
nsmd-jvh7p                     3/3     Running   2          116s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   1          76s
nsmd-jvh7p                     2/3     Running   4          2m29s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
nsm-vppagent-dataplane-fvbt2   1/1     Running   1          79s
nsmd-jvh7p                     3/3     Running   4          2m32s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ ls
admission-webhook-cfg.yaml  cluster-role-view.yaml        crossconnect-monitor.yaml  nsc.yaml                          vpn-gateway-nsc.yaml      vppagent-icmp-responder-nse.yaml
admission-webhook.yaml     crd-networkserviceendpoints.yaml  debug                nsmd.yaml                         vpn-gateway-nse.yaml      vppagent-nsc.yaml
cluster-role-admin.yaml     crd-networkservicemanagers.yaml   icmp-responder-nse.yaml    secure-intranet-connectivity.yaml  vppagent-dataplane.yaml
cluster-role-binding.yaml   crd-networkservices.yaml             jaeger.yaml             skydive.yaml                      vppagent-firewall-nse.yaml
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl create -f icmp-responder-nse.yaml
deployment.extensions/icmp-responder-nse created
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          4s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          4s
nsm-vppagent-dataplane-fvbt2          0/1     Running            3          3m1s
nsmd-jvh7p                            1/3     CrashLoopBackOff   5          4m14s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          23s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          23s
nsm-vppagent-dataplane-fvbt2          0/1     Completed          3          3m20s
nsmd-jvh7p                            2/3     CrashLoopBackOff   6          4m33s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          37s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          37s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   3          3m34s
nsmd-jvh7p                            2/3     CrashLoopBackOff   6          4m47s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          55s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          55s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   3          3m52s
nsmd-jvh7p                            2/3     CrashLoopBackOff   6          5m5s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          79s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          79s
nsm-vppagent-dataplane-fvbt2          0/1     Running            4          4m16s
nsmd-jvh7p                            2/3     CrashLoopBackOff   6          5m29s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          99s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          99s
nsm-vppagent-dataplane-fvbt2          1/1     Running            4          4m36s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          5m49s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          108s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          108s
nsm-vppagent-dataplane-fvbt2          1/1     Running            4          4m45s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          5m58s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m1s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m1s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          4m58s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m11s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m7s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m7s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m4s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m17s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m12s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m12s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m9s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m22s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m24s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m24s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m21s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m34s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m31s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m31s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m28s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m41s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m34s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m34s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m31s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m44s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m37s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m37s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m34s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          6m47s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          2m52s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          2m52s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m49s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          7m2s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
icmp-responder-nse-65f75fbc87-bvh96   0/1     Pending            0          3m1s
icmp-responder-nse-65f75fbc87-p9pt8   0/1     Pending            0          3m1s
nsm-vppagent-dataplane-fvbt2          0/1     CrashLoopBackOff   4          5m58s
nsmd-jvh7p                            2/3     CrashLoopBackOff   7          7m11s
stanislav@contivvpp:~/work/networkservicemesh/k8s/conf$ history

**Comment by edwarnicke** [comment] 2019-03-08 01:11
@stanislav-chlebec  I don't think the issue is 'running' per se.  I think the issue is that NSM uses the vpp-agent API to try to program the vpp instance... and thats when things go badly.  From the error message it looks like NSM tries to use the vpp-agent API to program:

```
time="2019-03-07T13:11:59Z" level=info msg="Sending DataChange to vppagent: Interfaces:<name:\"SRC-1\" type:TAP_INTERFACE enabled:true tap:<version:2 host_if_name:\"bi0hh7rqe9g\" > > Interfaces:<name:\"DST-1\" type:TAP_INTERFACE enabled:true tap:<version:2 host_if_name:\"bi0hh7rqea0\" > > XCons:<receive_interface:\"SRC-1\" transmit_interface:\"DST-1\" > XCons:<receive_interface:\"DST-1\" transmit_interface:\"SRC-1\" > LinuxInterfaces:<name:\"SRC-1\" description:\"Primary interface\" type:AUTO_TAP enabled:true ip_addresses:\"10.20.1.1/30\" host_if_name:\"nsm\" namespace:<type:FILE_REF_NS filepath:\"/proc/27547/ns/net\" > tap:<temp_if_name:\"bi0hh7rqe9g\" > > LinuxInterfaces:<name:\"DST-1\" description:\"NSM Endpoint\" type:AUTO_TAP enabled:true ip_addresses:\"10.20.1.2/30\" host_if_name:\"nsmmvcbx54V\" namespace:<type:FILE_REF_NS filepath:\"/proc/27329/ns/net\" > tap:<temp_if_name:\"bi0hh7rqea0\" > > LinuxArpEntries:<name:\"SRC-1_arp_0\" namespace:<type:FILE_REF_NS filepath:\"/proc/27547/ns/net\" > interface:\"SRC-1\" state:<> ip_addr:\"10.32.0.6\" hw_address:\"be:12:4c:d1:5d:ce\" > LinuxRoutes:<name:\"SRC-1_route_0\" namespace:<type:FILE_REF_NS filepath:\"/proc/27547/ns/net\" > interface:\"SRC-1\" description:\"Route to 8.8.8.8/30\" dst_ip_addr:\"8.8.8.8/30\" gw_addr:\"10.20.1.2\" > "
```

That's when we get the VPPAPI error from the ARM version.

**Comment by nickolaev** [comment] 2019-03-12 09:32
#828 was merged so the particular case of building the images is solved. Now there is an issue with running VPP on ARM64, and more specifically what @edwarnicke had mentioned.

@rdimitrov @stanislav-chlebec  shall we open another issue to track it or keep this one?

**Comment by stanislav-chlebec** [comment] 2019-03-12 09:36
we can keep this one IMHO

**Comment by stanislav-chlebec** [comment] 2019-03-13 12:52
I am trying to reproduce the VPPApiError: Initialization Failed
I see that after I set up  Kubernetes on my arm64-baremeteal machine via
./scripts/terraform/start-master.sh
and manually joined other arm64-baremetal machine
```
stanislav@contivvpp:~/work/stanislavchlebec/networkservicemesh/networkservicemesh$ kubectl get pods -n kube-system
NAME                                READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-dp8bk            1/1     Running   0          15m
coredns-86c58d9df4-mch2s            1/1     Running   0          15m
etcd-contivvpp                      1/1     Running   0          15m
kube-apiserver-contivvpp            1/1     Running   0          15m
kube-controller-manager-contivvpp   1/1     Running   0          14m
kube-proxy-v4pzs                    1/1     Running   0          14m
kube-proxy-xzw4r                    1/1     Running   0          15m
kube-scheduler-contivvpp            1/1     Running   0          15m
weave-net-4jsqm                     2/2     Running   0          15m
weave-net-ncf2k                     2/2     Running   0          14m
```
Now I could deploy via
make k8s-infra-deploy
but I can see that there are involved other docker images
DEPLOY_INFRA = $(DEPLOY_TRACING) $(DEPLOY_WEBHOOK) $(DEPLOY_NSM) $(DEPLOY_MONITOR)
which supossedly should by arm64 compatible (I mean jaeger and admission-webhook)

My question is if these two images are needed for NSM deployment?

**Comment by stanislav-chlebec** [comment] 2019-03-13 12:54
```
stanislav@contivvpp:~/work/stanislavchlebec/networkservicemesh/networkservicemesh$ make k8s-infra-deploy
Deleting k8s/conf/jaeger.yaml
jaeger does not exist and thus cannot be deleted
Uninstalling webhook...
admission-webhook-cfg does not exist and thus cannot be deleted
Deleting k8s/conf/admission-webhook.yaml
admission-webhook does not exist and thus cannot be deleted
Deleting nsm-admission-webhook-certs secret...
nsm-admission-webhook-certs does not exist and thus cannot be deleted
Deleting k8s/conf/nsmd.yaml
nsmd does not exist and thus cannot be deleted
Deleting k8s/conf/vppagent-dataplane.yaml
vppagent-dataplane does not exist and thus cannot be deleted
Deleting k8s/conf/crossconnect-monitor.yaml
crossconnect-monitor does not exist and thus cannot be deleted
Deleting k8s/conf/skydive.yaml
skydive does not exist and thus cannot be deleted
/bin/bash: vagrant: command not found
.mk/vagrant.mk:17: recipe for target 'vagrant-start' failed
make: *** [vagrant-start] Error 127

```

**Comment by rdimitrov** [comment] 2019-03-13 13:03
@stanislav-chlebec Indeed, you can skip them for testing - I've done the same 👍 

You can have a look at the latest 2 commits for how I've done it [here!](https://github.com/rdimitrov/networkservicemesh/commits/rdimitrov/dev-branch-arm64)

**Comment by stanislav-chlebec** [comment] 2019-04-04 08:42
@rdimitrov 
After some time I returned to this issue.
1
I welcome that the NSM project upgraded to ligato/vpp-agent:latest (version 2)
2
I followed your modifications in previous comment.

I tried now to deploy minimal NSMgr + Dataplane deployment on my bare-metal two Cavium ThunderX servers. Here is more about how the servers are configured: https://github.com/contiv/vpp/blob/master/docs/arm64/MANUAL_INSTALL_CAVIUM.md

Now successfully after setuping of hugepages in k8s/conf/vppagent-dataplane.yaml.
```
diff --git a/k8s/conf/vppagent-dataplane.yaml b/k8s/conf/vppagent-dataplane.yaml
index 8bdf7399..f16aff05 100644
--- a/k8s/conf/vppagent-dataplane.yaml
+++ b/k8s/conf/vppagent-dataplane.yaml
@@ -19,6 +19,8 @@ spec:
           image: networkservicemesh/vppagent-dataplane:latest
           imagePullPolicy: IfNotPresent
           env:
+#           - name: RETAIN_SUPERVISOR
+#             value: "y"
             - name: NSM_DATAPLANE_SRC_IP
               valueFrom:
                 fieldRef:
@@ -43,9 +45,14 @@ spec:
             timeoutSeconds: 3
           resources:
             limits:
-              cpu: 1
+              hugepages-1Gi: 2Gi
+              memory: 2Gi
             requests:
-              cpu: 1m
+              cpu: 250m
+#           limits:
+#             cpu: 1
+#           requests:
+#             cpu: 1m
       volumes:
         - hostPath:
             path: /var/lib/networkservicemesh
stanislav@contivvpp:~/work/stanislavchlebec/networkservicemesh$ 
```
Note: The variable `RETAIN_SUPERVISOR` is for preventing of restart in case that there are crashes.
Without hugepages VPP does not start and the contaners "nsm-vppagent-dataplane" crashed.

```
stanislav@contivvpp:~/work/stanislavchlebec/networkservicemesh$ ./p4
NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE        NOMINATED NODE   READINESS GATES
coredns-86c58d9df4-kzr8j            1/1     Running   0          90m   10.32.0.5       contivvpp   <none>           <none>
coredns-86c58d9df4-nchvt            1/1     Running   0          90m   10.32.0.6       contivvpp   <none>           <none>
etcd-contivvpp                      1/1     Running   0          91m   147.75.72.194   contivvpp   <none>           <none>
kube-apiserver-contivvpp            1/1     Running   0          91m   147.75.72.194   contivvpp   <none>           <none>
kube-controller-manager-contivvpp   1/1     Running   0          91m   147.75.72.194   contivvpp   <none>           <none>
kube-proxy-dn4h9                    1/1     Running   0          74m   147.75.98.202   vppagent    <none>           <none>
kube-proxy-pqjz9                    1/1     Running   0          90m   147.75.72.194   contivvpp   <none>           <none>
kube-scheduler-contivvpp            1/1     Running   0          91m   147.75.72.194   contivvpp   <none>           <none>
weave-net-7zpcx                     2/2     Running   1          74m   147.75.98.202   vppagent    <none>           <none>
weave-net-hfr4r                     2/2     Running   1          90m   147.75.72.194   contivvpp   <none>           <none>
NAME                                    READY   STATUS    RESTARTS   AGE     IP              NODE        NOMINATED NODE   READINESS GATES
nsm-admission-webhook-f78fd5b95-zdl8k   1/1     Running   0          2m23s   10.36.0.0       vppagent    <none>           <none>
nsm-vppagent-dataplane-5w5rv            1/1     Running   0          105s    147.75.72.194   contivvpp   <none>           <none>
nsm-vppagent-dataplane-fdszg            1/1     Running   0          105s    147.75.98.202   vppagent    <none>           <none>
nsmgr-dnll6                             3/3     Running   0          106s    10.36.0.1       vppagent    <none>           <none>
nsmgr-tb2sn                             3/3     Running   0          106s    10.32.0.7       contivvpp   <none>           <none>
stanislav@contivvpp:~/work/stanislavchlebec/networkservicemesh$ 

```

There are no errors in logs
```

masterIP=`kubectl get nodes -o wide --no-headers=true | grep master | awk '{print $6}'`
notmasterIP=`kubectl get nodes -o wide --no-headers=true | grep -v master | awk '{print $6}'`
nsmvppagentcontainer1=`kubectl get pods -o wide --no-headers=true --include-uninitialized  | grep $masterIP | awk '{print $1}' | grep 'nsm-vppagent-dataplane'`
nsmvppagentcontainer2=`kubectl get pods -o wide --no-headers=true --include-uninitialized  | grep $notmasterIP | awk '{print $1}' | grep 'nsm-vppagent-dataplane'`
kubectl logs $nsmvppagentcontainer1 | grep error
kubectl logs $nsmvppagentcontainer2 | grep error


```

**Comment by edwarnicke** [comment] 2019-04-08 17:02
@stanislav-chlebec Did you ever get this into CI?

**Comment by nickolaev** [comment] 2019-05-09 05:15
Putting a link to buildx crosscompilstion for docker just in case we decide to use it

http://excoder.blogspot.com/2019/05/docker-buildx-from-scratch.html?m=1

**Comment by stanislav-chlebec** [comment] 2019-06-07 07:48
Hello 
After fullfiling my other duties I returned to the project.
Could we discuss what we want to achieve with arm64 platform?
So far I know that we should suggest a way how to crosscompile networkservicemesh docker images.

**Comment by nickolaev** [comment] 2019-06-07 11:56
So it would make sense if we had a CI pipeline for ARM64. I mean even if we cross-compile the images and never test them, we can not be sure of what wee actually ship.
So cross-compilation is not somethin I'd aspire to. Looking at the logs here, I see that we actually we never managed to run NSM's forwarding plane (VPP) on that platform? Do you by any chance have a setup where that can be run?

**Comment by nickolaev** [comment] 2019-06-10 13:19
One more link for reference: https://medium.com/@carlosedp/cross-building-arm64-images-on-docker-desktop-254d1e0bc1f9

**Closed** 2019-07-17 14:41 UTC
Labels: wontfix
